### PR TITLE
Create flathub.json for eol rebase

### PR DESCRIPTION
**Pull request by mlm-games**

### CODE REVIEW

**Comment by bbhtt** [comment]
You need to submit it first. and the id should be `io.github.mlm_games.asteroids_revenge` `mlm-games` is not a valid id.

**Comment by mlm-games** [comment]
> You need to submit it first. and the id should be `io.github.mlm_games.asteroids_revenge` `mlm-games` is not a valid id.

would it allow for verification using mlm-games.github.io with mlm_games?

**Comment by bbhtt** [comment]
yes the website can convert `_` to `-`.

**Comment by mlm-games** [comment]
i wont be merging it now

**Comment by mlm-games** [comment]
bot, build io.github.mlm.asteroids_revenge

**Pull request merged**
